In [210]:
# merge with country_medal_count on country code

In [211]:
import pandas as pd
import numpy as np

In [212]:
# load in data
world_indicators = pd.read_csv("rawData/World_Development_Indicator/Indicator_Data_1960-2023.csv")
country_medal_count = pd.read_csv("rawData/Sum_Win_Olympics_1896-2022/Olympic_Games_Medal_Tally.csv")

In [213]:
# drop column
world_indicators = world_indicators.drop(columns=['Series Code', 'Country Name'])
# drop regions
world_indicators = world_indicators[:1519]

In [214]:
# sub in NaN
world_indicators = world_indicators.replace('..', np.nan)

In [215]:
# years into rows
world_indicators = world_indicators.melt(id_vars=['Country Code', 'Series Name'], var_name='Year')
world_indicators['value'] = pd.to_numeric(world_indicators['value'], errors='coerce')
world_indicators.head(20)

,Country Code,Series Name,Year,value
0,AFG,GDP per capita (current US$),1960 [YR1960],NaN
1,AFG,GDP (current US$),1960 [YR1960],NaN
2,AFG,Adjusted savings: education expenditure (curre...,1960 [YR1960],NaN
3,AFG,Current health expenditure per capita (current...,1960 [YR1960],NaN
4,AFG,Human capital index (HCI) (scale 0-1),1960 [YR1960],NaN
5,AFG,"Life expectancy at birth, total (years)",1960 [YR1960],3.253500e+01
6,AFG,"Population, total",1960 [YR1960],9.035043e+06
7,ALB,GDP per capita (current US$),1960 [YR1960],NaN
8,ALB,GDP (current US$),1960 [YR1960],NaN
9,ALB,Adjusted savings: education expenditure (curre...,1960 [YR1960],NaN
10,ALB,Current health expenditure per capita (current...,1960 [YR1960],NaN
11,ALB,Human capital index (HCI) (scale 0-1),1960 [YR1960],NaN
12,ALB,"Life expectancy at birth, total (years)",1960 [YR1960],5.443900e+01
13,ALB,"Population, total",1960 [YR1960],1.608800e+06
14,DZA,GDP per capita (current US$),1960 [YR1960],2.383925e+02
15,DZA,GDP (current US$),1960 [YR1960],2.723615e+09
16,DZA,Adjusted savings: education expenditure (curre...,1960 [YR1960],NaN
17,DZA,Current health expenditure per capita (current...,1960 [YR1960],NaN
18,DZA,Human capital index (HCI) (scale 0-1),1960 [YR1960],NaN
19,DZA,"Life expectancy at birth, total (years)",1960 [YR1960],4.053200e+01

In [216]:
# series name into columns
world_indicators = world_indicators.pivot_table(index=['Country Code', 'Year'], columns='Series Name', values='value')
world_indicators.head(10)

Series Name                 Adjusted savings: education expenditure (current US$)  \
Country Code Year
ABW          1960 [YR1960]                                                NaN
             1961 [YR1961]                                                NaN
             1962 [YR1962]                                                NaN
             1963 [YR1963]                                                NaN
             1964 [YR1964]                                                NaN
             1965 [YR1965]                                                NaN
             1966 [YR1966]                                                NaN
             1967 [YR1967]                                                NaN
             1968 [YR1968]                                                NaN
             1969 [YR1969]                                                NaN

Series Name                 Current health expenditure per capita (current US$)  \
Country Code Year
ABW          1960 [YR1960]                                                NaN
             1961 [YR1961]                                                NaN
             1962 [YR1962]                                                NaN
             1963 [YR1963]                                                NaN
             1964 [YR1964]                                                NaN
             1965 [YR1965]                                                NaN
             1966 [YR1966]                                                NaN
             1967 [YR1967]                                                NaN
             1968 [YR1968]                                                NaN
             1969 [YR1969]                                                NaN

Series Name                 GDP (current US$)  GDP per capita (current US$)  \
Country Code Year
ABW          1960 [YR1960]                NaN                           NaN
             1961 [YR1961]                NaN                           NaN
             1962 [YR1962]                NaN                           NaN
             1963 [YR1963]                NaN                           NaN
             1964 [YR1964]                NaN                           NaN
             1965 [YR1965]                NaN                           NaN
             1966 [YR1966]                NaN                           NaN
             1967 [YR1967]                NaN                           NaN
             1968 [YR1968]                NaN                           NaN
             1969 [YR1969]                NaN                           NaN

Series Name                 Human capital index (HCI) (scale 0-1)  \
Country Code Year
ABW          1960 [YR1960]                                    NaN
             1961 [YR1961]                                    NaN
             1962 [YR1962]                                    NaN
             1963 [YR1963]                                    NaN
             1964 [YR1964]                                    NaN
             1965 [YR1965]                                    NaN
             1966 [YR1966]                                    NaN
             1967 [YR1967]                                    NaN
             1968 [YR1968]                                    NaN
             1969 [YR1969]                                    NaN

Series Name                 Life expectancy at birth, total (years)  \
Country Code Year
ABW          1960 [YR1960]                                   64.152
             1961 [YR1961]                                   64.537
             1962 [YR1962]                                   64.752
             1963 [YR1963]                                   65.132
             1964 [YR1964]                                   65.294
             1965 [YR1965]                                   65.502
             1966 [YR1966]                                   66.063
             1967 [YR1967]                                   66.439
             1968 [YR1968]                                   66.757
             1969 [YR1969]                                   67.168

Series Name                 Population, total
Country Code Year
ABW          1960 [YR1960]            54922.0
             1961 [YR1961]            55578.0
             1962 [YR1962]            56320.0
             1963 [YR1963]            57002.0
             1964 [YR1964]            57619.0
             1965 [YR1965]            58190.0
             1966 [YR1966]            58694.0
             1967 [YR1967]            58990.0
             1968 [YR1968]            59069.0
             1969 [YR1969]            59052.0

In [217]:
# reset index
world_indicators = world_indicators.reset_index().rename_axis(columns=None)
world_indicators.head()

,Country Code,Year,Adjusted savings: education expenditure (current US$),Current health expenditure per capita (current US$),GDP (current US$),GDP per capita (current US$),Human capital index (HCI) (scale 0-1),"Life expectancy at birth, total (years)","Population, total"
0,ABW,1960 [YR1960],NaN,NaN,NaN,NaN,NaN,64.152,54922.0
1,ABW,1961 [YR1961],NaN,NaN,NaN,NaN,NaN,64.537,55578.0
2,ABW,1962 [YR1962],NaN,NaN,NaN,NaN,NaN,64.752,56320.0
3,ABW,1963 [YR1963],NaN,NaN,NaN,NaN,NaN,65.132,57002.0
4,ABW,1964 [YR1964],NaN,NaN,NaN,NaN,NaN,65.294,57619.0

In [218]:
# extract year
world_indicators['Year'] = world_indicators['Year'].str.extract(r'(\d{4})').astype(int)
world_indicators.head()

,Country Code,Year,Adjusted savings: education expenditure (current US$),Current health expenditure per capita (current US$),GDP (current US$),GDP per capita (current US$),Human capital index (HCI) (scale 0-1),"Life expectancy at birth, total (years)","Population, total"
0,ABW,1960,NaN,NaN,NaN,NaN,NaN,64.152,54922.0
1,ABW,1961,NaN,NaN,NaN,NaN,NaN,64.537,55578.0
2,ABW,1962,NaN,NaN,NaN,NaN,NaN,64.752,56320.0
3,ABW,1963,NaN,NaN,NaN,NaN,NaN,65.132,57002.0
4,ABW,1964,NaN,NaN,NaN,NaN,NaN,65.294,57619.0

In [219]:
print(country_medal_count.shape)
print(world_indicators.shape)

(1807, 9)
(13858, 9)

In [220]:
# extract season
season_pattern = r'(Summer|Winter|Equestrian|Intercalated)'
country_medal_count['season'] = country_medal_count['edition'].str.extract(season_pattern)
country_medal_count = country_medal_count.drop(columns='edition')
country_medal_count.head()

,edition_id,year,country,country_noc,gold,silver,bronze,total,season
0,1,1896,United States,USA,11,7,2,20,Summer
1,1,1896,Greece,GRE,10,18,19,47,Summer
2,1,1896,Germany,GER,6,5,2,13,Summer
3,1,1896,France,FRA,5,4,2,11,Summer
4,1,1896,Great Britain,GBR,2,3,2,7,Summer

In [221]:
# country_data = pd.merge(country_medal_count, world_indicators, left_on=['country_noc', 'year'], right_on=['Country Code', 'Year'], how='left')
# country_data.tail()

In [222]:
# convert to strings
country_medal_count['country_noc'] = country_medal_count['country_noc'].astype(str)
world_indicators['Country Code'] = world_indicators['Country Code'].astype(str)

# convert to integers
country_medal_count['year'] = country_medal_count['year'].astype(int)
world_indicators['Year'] = world_indicators['Year'].astype(int)

#merge
# country_data = pd.merge(
#     country_medal_count,
#     world_indicators,
#     left_on=['country_noc', 'year'],
#     right_on=['Country Code', 'Year'],
#     how='left'
# )

In [223]:
# # unique country codes in world_indicators
# world_codes = world_indicators['Country Code'].unique()

# # find missing country_noc values for each year in the merged dataset
# missing_codes_all_years = country_data[~country_data['country_noc'].isin(world_codes)]['country_noc'].unique()

# # Print the missing country codes
# len(missing_codes_all_years)

In [224]:
# dictionary 
code_dict = {
    'DZA':'ALG',
    'BHS':'BAH',
    'BRB':'BAR',
    'BMU':'BER',
    'BWA':'BOT',
    'BGR':'BUL',
    'CRI':'CRC',
    'HRV':'CRO',
    'DNK':'DEN',
    'FJI':'FIJ',
    'DEU':'GER',
    'GRC':'GRE',
    'GRD':'GRN',
    'GTM':'GUA',
    'HTI':'HAI',
    'IDN':'INA',
    'IRN':'IRI',
    'VIR':'ISV',
    'XKX':'KOS',
    'SAU':'KSA',
    'KWT':'KUW',
    'LVA':'LAT',
    'MNG':'MGL',
    'MYS':'MAS',
    'NLD':'NED',
    'NGA':'NGR',
    'NER':'NIG',
    'PRY':'PAR',
    'PHL':'PHI',
    'PRT':'POR',
    'PRI':'PUR',
    'ZAF':'RSA',
    'ASM':'SAM',
    'SVN':'SLO',
    'LKA':'SRI',
    'SSD':'SUD',
    'TZA':'TAN',
    'TON':'TGA',
    'TGO':'TOG',
    'ARE':'UAE',
    'RUS':'URS',
    'URY':'URU',
    'VNM':'VIE',
    'ZMB':'ZAM',
    'ZWE':'ZIM'
}

In [225]:
# Replace current values in the country column with the country values from the dictionary based on country_noc
world_indicators['Country Code'] = world_indicators['Country Code'].map(code_dict)

In [226]:
# merge
country_data = pd.merge(
    country_medal_count,
    world_indicators,
    left_on=['country_noc', 'year'],
    right_on=['Country Code', 'Year'],
    how='left'
)

In [227]:
# unique country codes in world_indicators
world_codes = world_indicators['Country Code'].unique()

# find missing country_noc values for each year in the merged dataset
missing_codes_all_years = country_data[~country_data['country_noc'].isin(world_codes)]['country_noc'].unique()

# Print the missing country codes
len(missing_codes_all_years)

109

In [228]:
#country_data.to_csv('full_country.csv', index=False)